In [11]:
import pandas as pd
from joblib import load

In [39]:
model_binary = load("../../generated_models/Binary_model/svc_model.joblib")
model_hfb_cps = load("../../generated_models/HFB_CPs_model/knn_model.joblib")
model_hfb_class = load("../../generated_models/HFB_model/svc_trained_model.joblib")

In [13]:
df_esme = pd.read_csv("../../results/mapping_p_salina/esme.csv")
df_esme

,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,p_9,...,p_1271,p_1272,p_1273,p_1274,p_1275,p_1276,p_1277,p_1278,p_1279,id
0,0.127274,1.124596,-0.422021,-0.419250,-0.154063,0.428913,0.602637,0.509053,0.181203,-1.382456,...,0.185947,-0.147054,0.399785,0.462824,-0.742469,1.118556,0.325974,0.694428,0.003051,g1.t1
1,-1.697857,-0.023073,0.818991,-0.031624,-0.553273,0.505217,0.133630,-0.131556,0.219252,-3.115513,...,-0.596637,-0.392206,-0.502288,-0.003617,-0.874744,2.156140,0.145597,-1.672090,-0.464309,g3.t1
2,1.148784,-0.137593,-0.949296,0.203425,1.159509,-0.672439,0.016368,0.591740,0.644622,-0.619736,...,-0.064922,-0.271578,1.107259,1.241736,-0.434262,-0.164266,-0.031240,0.349442,0.343006,g4.t1
3,-0.382898,0.798589,0.253340,-0.092391,0.199944,-0.117151,1.127868,-0.647408,0.295163,-1.810393,...,0.407911,-0.977357,0.681780,1.106050,-0.085772,1.913908,0.200405,-0.050173,0.604931,g5.t1
4,1.182175,0.086073,-0.237252,-0.746092,-0.046632,1.088030,0.482073,-0.149021,0.919429,-0.677131,...,0.191825,-0.568584,0.588480,0.545412,-0.508119,0.857671,0.138422,1.343540,0.309474,g6.t1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8575,-3.080764,0.772672,1.586506,0.379552,1.086607,1.490179,-1.322483,-0.170182,0.595682,-4.417612,...,-0.571477,-0.396637,-1.172388,-0.016480,-2.054996,2.391960,1.562938,-1.806554,0.281334,g9531.t1
8576,-1.718696,1.359880,-0.409170,-0.434491,1.454223,1.445221,-0.797585,1.570162,0.127949,-0.279570,...,0.318517,0.277043,1.643190,0.424937,-0.065251,-0.066759,0.036826,1.135144,-0.831179,g9532.t1
8577,-1.932215,1.927978,-0.651487,0.179265,1.770016,1.486641,-0.689742,1.340597,0.170345,-0.788864,...,0.804942,0.153020,1.586615,0.694647,-0.202858,0.128837,-0.284397,1.001016,-0.657853,g9533.t1
8578,-2.230117,-0.966147,0.398479,-0.191836,-0.548050,0.830886,-1.082974,1.105324,0.242249,-3.348654,...,-0.779667,-0.618166,-1.292164,-0.523405,-0.987652,1.688912,1.437224,-0.770764,0.052012,g9534.t1
8579,-2.230044,1.567469,-0.643342,0.447643,1.678517,1.352276,-0.580200,1.154014,0.055749,-0.920404,...,0.922393,0.362596,1.068861,0.299771,0.345325,-0.025346,-0.498588,0.867588,-0.245905,g9535.t1

In [14]:
df_prottrans_uniref = pd.read_csv("../../results/mapping_p_salina/prottrans_t5_uniref.csv")
df_prottrans_uniref

,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,p_9,...,p_1015,p_1016,p_1017,p_1018,p_1019,p_1020,p_1021,p_1022,p_1023,id
0,0.010910,0.051324,0.040499,0.051030,0.003663,0.049616,0.024161,-0.069393,0.012285,-0.004284,...,-0.014562,-0.002804,-0.021060,0.043286,0.003781,0.008410,0.040269,0.004928,-0.013716,g1.t1
1,0.005720,-0.073669,0.065392,-0.026735,-0.016126,0.034192,-0.049892,-0.105832,-0.030050,-0.016473,...,-0.024740,-0.007580,-0.016437,0.016228,0.012258,-0.046204,-0.076518,-0.035398,0.016512,g3.t1
2,0.097609,0.026509,0.011354,0.004036,-0.003633,0.057089,-0.041337,-0.105890,0.020714,-0.045930,...,-0.015658,-0.048098,-0.019219,0.032493,0.004445,0.009418,-0.011150,0.007104,0.010465,g4.t1
3,0.066908,0.001784,0.015602,0.017649,-0.027069,0.070193,-0.087072,-0.097493,-0.018878,0.001497,...,-0.028620,0.019585,-0.036169,-0.013101,0.036175,-0.014633,-0.025768,0.003400,0.031255,g5.t1
4,0.037910,0.031696,0.023447,0.020645,0.005123,0.035256,-0.016166,-0.024998,-0.004620,-0.033115,...,-0.001335,-0.023320,-0.081601,0.067333,-0.027767,0.016251,-0.022318,-0.041699,-0.015581,g6.t1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8575,0.061616,0.075325,-0.012016,-0.021676,0.047616,-0.000427,-0.005360,-0.059070,0.062260,-0.014524,...,-0.042806,0.021388,-0.000296,-0.071654,0.007117,0.025161,0.047031,-0.001706,0.002735,g9531.t1
8576,0.169295,0.176083,0.104286,0.100811,0.036945,-0.114098,0.027106,-0.110211,-0.175071,0.039677,...,0.055369,0.010015,-0.171363,0.081441,-0.003361,0.075094,-0.119118,-0.005617,0.071013,g9532.t1
8577,0.115742,0.180007,0.139850,0.048839,0.008144,-0.078234,0.051281,-0.072916,-0.119424,-0.021339,...,0.009504,-0.009791,-0.131952,0.054586,0.002611,0.099867,-0.153631,0.025099,0.089857,g9533.t1
8578,0.070100,-0.048279,0.100932,-0.066162,0.132187,-0.043737,0.026084,-0.052590,0.028904,-0.007066,...,-0.071176,0.055726,-0.102218,-0.068117,0.005321,0.000050,-0.038823,0.075625,0.095217,g9534.t1
8579,0.077048,0.176956,0.143689,0.017715,0.027101,-0.091460,0.045354,-0.056640,-0.076093,-0.007648,...,-0.008680,-0.012126,-0.130391,0.041196,0.013524,0.126737,-0.140603,0.030683,0.089030,g9535.t1

In [15]:
df_prottrans_xlu50 = pd.read_csv("../../results/mapping_p_salina/prottrans_t5_xlu50.csv")
df_prottrans_xlu50

,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,p_9,...,p_1015,p_1016,p_1017,p_1018,p_1019,p_1020,p_1021,p_1022,p_1023,id
0,0.008766,0.033203,0.038940,0.056793,-0.009010,0.027817,0.018661,-0.064880,0.007561,-0.023102,...,-0.018051,-0.005116,-0.017685,0.048859,0.005066,0.002357,0.043335,0.013062,-0.021225,g1.t1
1,0.007027,-0.053040,0.042542,-0.028244,-0.026367,0.045959,-0.030838,-0.093323,-0.031067,-0.024597,...,-0.022369,0.003023,-0.012131,0.016495,-0.000181,-0.035156,-0.083435,-0.006615,0.020920,g3.t1
2,0.066345,0.039368,0.028061,0.003229,-0.006268,0.053284,-0.066345,-0.100281,0.010704,-0.045013,...,-0.010117,-0.040863,-0.019211,0.028992,0.023773,-0.002571,-0.019226,0.018082,0.005009,g4.t1
3,0.050171,0.011162,0.025650,0.017731,-0.021561,0.056885,-0.096497,-0.096130,-0.008308,-0.020386,...,-0.018509,0.004349,-0.012245,-0.017441,0.039703,-0.009567,-0.021011,-0.000210,0.026123,g5.t1
4,0.018677,0.050781,0.027008,0.012550,-0.008842,0.030807,-0.013626,-0.014984,0.009109,-0.030716,...,-0.013313,-0.003674,-0.072449,0.056030,-0.019745,-0.010719,-0.018051,-0.013496,-0.009445,g6.t1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8575,0.061096,0.025177,0.014610,0.003555,0.011986,0.008507,-0.030212,-0.038055,0.034027,-0.017929,...,-0.064087,-0.016647,0.010246,-0.023605,0.002604,0.041992,0.029572,0.020905,-0.007561,g9531.t1
8576,0.134521,0.156494,0.135376,0.060181,0.012589,-0.111328,0.040466,-0.065979,-0.154297,-0.014786,...,0.079773,-0.032257,-0.135010,0.083923,-0.006977,0.025436,-0.122437,0.016205,0.007980,g9532.t1
8577,0.093994,0.166626,0.161743,0.012695,-0.003330,-0.089661,0.036499,-0.008087,-0.099487,-0.038025,...,0.046417,-0.038422,-0.103516,0.069580,-0.005127,0.059448,-0.152100,0.053894,0.046143,g9533.t1
8578,0.054016,-0.043549,0.065002,-0.019821,0.118103,-0.075989,0.012390,-0.029663,0.049164,-0.005035,...,-0.052979,0.033356,-0.065552,-0.079224,0.010628,-0.030243,-0.039764,0.121033,0.080261,g9534.t1
8579,0.064209,0.169556,0.157227,-0.007641,0.023376,-0.105347,0.021469,0.002428,-0.073792,-0.013840,...,0.040863,-0.043579,-0.106323,0.043182,0.009995,0.077271,-0.147095,0.053864,0.050934,g9535.t1

In [16]:
id_esme = df_esme["id"]
df_esme = df_esme.drop(columns=["id"])

In [17]:
predictions_binary = model_binary.predict(df_esme)
predictions_binary

/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:413: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(

array(['Negative', 'Negative', 'Negative', ..., 'Negative', 'Negative',
       'Negative'], dtype=object)

In [44]:
predictions_binary_prob = model_binary.predict_proba(df_esme)
predictions_binary_prob_df = pd.DataFrame(data=predictions_binary_prob, columns=["Negative", "Positive"])
predictions_binary_prob_df

/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:413: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(

      Negative      Positive
0     0.994700  5.299874e-03
1     0.990550  9.450324e-03
2     0.972905  2.709529e-02
3     0.998544  1.456396e-03
4     0.990354  9.645578e-03
...        ...           ...
8575  1.000000  1.000000e-07
8576  0.988591  1.140935e-02
8577  0.871314  1.286865e-01
8578  0.982254  1.774621e-02
8579  0.971534  2.846616e-02

[8580 rows x 2 columns]

In [47]:
predictions_binary_prob_df["id"] = id_esme.values
predictions_binary_prob_df["is_HFB-CP"] = predictions_binary
predictions_binary_prob_df

      Negative      Positive        id is_HFB-CP
0     0.994700  5.299874e-03     g1.t1  Negative
1     0.990550  9.450324e-03     g3.t1  Negative
2     0.972905  2.709529e-02     g4.t1  Negative
3     0.998544  1.456396e-03     g5.t1  Negative
4     0.990354  9.645578e-03     g6.t1  Negative
...        ...           ...       ...       ...
8575  1.000000  1.000000e-07  g9531.t1  Negative
8576  0.988591  1.140935e-02  g9532.t1  Negative
8577  0.871314  1.286865e-01  g9533.t1  Negative
8578  0.982254  1.774621e-02  g9534.t1  Negative
8579  0.971534  2.846616e-02  g9535.t1  Negative

[8580 rows x 4 columns]

In [48]:
predictions_binary_positive = predictions_binary_prob_df[predictions_binary_prob_df["is_HFB-CP"] == "Positive"]
predictions_binary_negative = predictions_binary_prob_df[predictions_binary_prob_df["is_HFB-CP"] == "Negative"]

In [63]:
predictions_positive = predictions_binary_positive[predictions_binary_positive["Positive"]>=0.98]
predictions_positive

          Negative  Positive        id is_HFB-CP
9     1.698485e-07  1.000000    g11.t1  Positive
23    3.671221e-08  1.000000    g28.t1  Positive
25    4.582322e-07  1.000000    g30.t1  Positive
35    1.776694e-02  0.982233    g44.t1  Positive
51    2.437843e-12  1.000000    g61.t1  Positive
...            ...       ...       ...       ...
8400  1.387839e-02  0.986122  g9347.t1  Positive
8414  6.044151e-03  0.993956  g9362.t1  Positive
8468  9.416461e-11  1.000000  g9420.t1  Positive
8483  1.640372e-05  0.999984  g9437.t1  Positive
8494  6.954099e-14  1.000000  g9448.t1  Positive

[236 rows x 4 columns]

In [65]:
df_merge_uniref = df_prottrans_uniref.merge(right=predictions_positive, on="id")
df_merge_id = df_merge_uniref["id"]

df_merge_uniref = df_merge_uniref.drop(columns=["id", "is_HFB-CP", "Negative", "Positive"])
df_merge_uniref

,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,p_9,...,p_1014,p_1015,p_1016,p_1017,p_1018,p_1019,p_1020,p_1021,p_1022,p_1023
0,-0.072744,0.082655,0.187020,-0.041911,-0.016102,-0.028781,-0.063080,-0.068804,0.020665,-0.010264,...,-0.003472,-0.030230,-0.025789,-0.006364,0.082703,-0.015740,0.008662,0.101781,0.016293,0.160682
1,-0.029599,-0.006863,0.109503,0.000437,-0.064318,0.034332,-0.004918,-0.101900,0.067890,-0.049941,...,-0.025929,0.000881,-0.003564,-0.076333,0.022646,0.047604,-0.005990,0.050832,-0.008490,0.023119
2,0.016117,0.052026,0.139802,0.008488,0.016776,-0.038354,-0.035516,-0.082860,-0.022855,-0.048121,...,-0.087613,-0.022682,-0.020503,-0.030420,0.040591,-0.031006,-0.015287,-0.002542,0.023150,0.031008
3,-0.068671,0.001602,0.145661,0.000273,-0.037136,0.004515,-0.112923,-0.083583,-0.024765,-0.025216,...,-0.049214,0.009400,-0.007374,-0.017076,-0.011643,0.000158,0.058992,0.042106,0.076984,0.108982
4,-0.016718,0.140899,0.051747,0.033203,-0.152068,0.012433,-0.070004,-0.092179,0.063434,-0.059863,...,0.039221,0.020944,-0.010156,-0.115170,-0.003517,0.111938,0.010424,-0.031461,-0.020070,0.073754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,0.026857,-0.035349,0.058944,-0.055043,-0.058929,0.012052,-0.036597,-0.094851,0.038541,-0.027362,...,-0.088440,-0.016128,-0.058449,-0.106630,0.050030,-0.020314,-0.008022,0.002177,0.064871,0.037510
232,0.014149,0.028679,0.151037,0.019423,-0.024997,0.019433,-0.042231,-0.130258,-0.014925,0.034189,...,0.027318,-0.082293,-0.025267,-0.015191,0.022810,0.019798,-0.004375,-0.043723,0.026851,0.004865
233,-0.023369,0.151777,0.077177,0.072847,-0.140152,-0.024230,-0.070491,-0.131999,0.027290,-0.012191,...,0.065582,-0.039955,-0.022892,-0.098375,-0.035443,0.119237,0.006831,-0.045201,0.014427,0.085250
234,-0.009599,0.006336,0.164341,0.064626,-0.090624,-0.004164,-0.136624,-0.158938,-0.031483,-0.065226,...,-0.079368,-0.011779,-0.008723,-0.035066,-0.056158,-0.023660,-0.022938,0.043472,-0.023905,0.024186
235,-0.013862,0.049031,0.147426,-0.043293,-0.048644,-0.027712,-0.029784,-0.096189,0.012257,-0.049783,...,-0.003723,-0.094356,0.026799,-0.021195,0.033672,0.031536,0.066220,0.019412,-0.042565,0.018003

In [70]:
predictions_hfb_cps_prob = model_hfb_cps.predict_proba(df_merge_uniref)
predictions_hfb_cps = model_hfb_cps.predict(df_merge_uniref)

/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:413: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:413: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [106]:
df_predictions_hfb_cps = pd.DataFrame(data=predictions_hfb_cps_prob, columns=["CPs", "HFB"])
df_predictions_hfb_cps["id"] = df_merge_id.values
df_predictions_hfb_cps["predictions"] = predictions_hfb_cps

df_predictions_hfb_cps_HFB = df_predictions_hfb_cps[df_predictions_hfb_cps["predictions"] == "HFB"]
df_predictions_hfb_cps_CP = df_predictions_hfb_cps[df_predictions_hfb_cps["predictions"] == "CPs"]

df_predictions_hfb_cps["predictions"].value_counts()

predictions
HFB    219
CPs     17
Name: count, dtype: int64

In [76]:
df_predictions_hfb_cps_HFB = df_predictions_hfb_cps_HFB[df_predictions_hfb_cps_HFB["HFB"] == 1]
df_predictions_hfb_cps_HFB

     CPs  HFB        id predictions
0    0.0  1.0    g11.t1         HFB
1    0.0  1.0    g28.t1         HFB
3    0.0  1.0    g44.t1         HFB
4    0.0  1.0    g61.t1         HFB
5    0.0  1.0   g166.t1         HFB
..   ...  ...       ...         ...
231  0.0  1.0  g9347.t1         HFB
232  0.0  1.0  g9362.t1         HFB
233  0.0  1.0  g9420.t1         HFB
234  0.0  1.0  g9437.t1         HFB
235  0.0  1.0  g9448.t1         HFB

[188 rows x 4 columns]

In [107]:
df_predictions_hfb_cps_CP[df_predictions_hfb_cps_CP["CPs"] == 1]

     CPs  HFB        id predictions
61   1.0  0.0  g2314.t1         CPs
65   1.0  0.0  g2544.t1         CPs
66   1.0  0.0  g2654.t1         CPs
89   1.0  0.0  g3634.t1         CPs
180  1.0  0.0  g7021.t1         CPs
202  1.0  0.0  g7994.t1         CPs
209  1.0  0.0  g8291.t1         CPs
213  1.0  0.0  g8570.t1         CPs

In [77]:
df_merge_xlu50 = df_prottrans_xlu50.merge(right=df_predictions_hfb_cps_HFB, on="id")
df_merge_xlu50_id = df_merge_xlu50["id"]
df_merge_xlu50_to_predict = df_merge_xlu50.drop(columns=["id", "predictions", "CPs", "HFB"])
df_merge_xlu50_to_predict

,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,p_9,...,p_1014,p_1015,p_1016,p_1017,p_1018,p_1019,p_1020,p_1021,p_1022,p_1023
0,-0.075684,0.069580,0.142090,-0.038330,-0.019073,-0.025833,-0.104614,-0.083435,0.002848,-0.046234,...,0.004433,-0.011497,-0.015381,0.010155,0.094177,0.027130,-0.022034,0.098816,0.031372,0.130249
1,-0.027740,0.039886,0.104004,0.011559,-0.058350,0.032043,-0.021454,-0.099670,0.044098,-0.061188,...,-0.001118,0.018921,-0.037903,-0.091248,0.028870,0.030777,0.016312,0.041779,0.022018,-0.012741
2,-0.073730,0.003473,0.121887,0.009621,-0.022949,0.028687,-0.106506,-0.084534,-0.016113,-0.054626,...,-0.035095,0.021347,0.001372,-0.016678,-0.014977,0.029617,0.013939,0.056610,0.093872,0.088013
3,-0.006035,0.140869,0.044922,0.071411,-0.123657,-0.024582,-0.086731,-0.083862,0.060181,-0.051361,...,0.025375,0.006878,-0.032959,-0.109253,-0.007381,0.107361,0.019287,-0.008812,0.023148,0.014107
4,0.038055,-0.007740,0.045441,-0.060669,-0.054138,-0.059753,-0.031204,-0.100281,0.031555,-0.052429,...,-0.121521,-0.047485,-0.133545,0.018768,-0.021652,0.032318,0.010063,-0.013573,0.056091,0.014824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,0.021820,-0.019470,0.041687,-0.028824,-0.038544,-0.006367,-0.062927,-0.089722,0.054565,-0.039612,...,-0.079651,0.004841,-0.024902,-0.064941,0.066406,0.019043,-0.004269,0.035492,0.071899,0.010727
184,0.002666,0.025803,0.119324,0.017059,0.006721,0.042633,-0.059174,-0.133179,-0.036743,0.007080,...,-0.007263,-0.008072,-0.013809,-0.026657,0.008339,0.028183,-0.015442,-0.035797,0.062256,0.014420
185,-0.000803,0.157227,0.064453,0.131348,-0.114380,-0.049011,-0.109131,-0.105835,0.024017,-0.009895,...,0.032837,-0.037903,-0.057220,-0.088745,-0.026367,0.117676,0.028549,0.001248,0.050812,0.031281
186,-0.054382,-0.016006,0.157837,0.074707,-0.067200,-0.002186,-0.157227,-0.154175,-0.035339,-0.114502,...,-0.090698,0.009888,-0.015976,-0.001929,-0.028427,0.002724,-0.048187,0.079895,0.026733,0.024338
187,0.003263,0.063843,0.125732,-0.041107,-0.066650,-0.050232,-0.026215,-0.095947,0.016815,-0.067383,...,-0.028625,-0.074341,0.045746,-0.034882,0.019714,0.057709,0.049438,0.015900,-0.010544,0.013870

In [80]:
predictions_hfb_prob = model_hfb_class.predict_proba(df_merge_xlu50_to_predict.values)
predictions_hfb = model_hfb_class.predict(df_merge_xlu50_to_predict.values)

In [81]:
model_hfb_class.predict_proba(df_merge_xlu50_to_predict[:1])

/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:413: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(

array([[0.79813408, 0.20186592]])

In [82]:
model_hfb_class.predict(df_merge_xlu50_to_predict[:1])

/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:413: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(

array(['HFB Class I'], dtype=object)

In [83]:
df_predictions_hfb = pd.DataFrame(data=predictions_hfb_prob, columns=['HFB Class I', 'HFB Class II'])
df_predictions_hfb["id"] = df_merge_xlu50_id.values
df_predictions_hfb["predictions"] = predictions_hfb
df_predictions_hfb["predictions"].value_counts()

predictions
HFB Class I     181
HFB Class II      7
Name: count, dtype: int64

In [101]:
df_class_2 = df_predictions_hfb[df_predictions_hfb["predictions"] == "HFB Class II"]
df_class_2.describe()

       HFB Class I  HFB Class II
count     7.000000      7.000000
mean      0.178464      0.821536
std       0.205678      0.205678
min       0.011628      0.508055
25%       0.017668      0.661635
50%       0.033607      0.966393
75%       0.338365      0.982332
max       0.491945      0.988372

In [98]:
df_class_1 = df_predictions_hfb[df_predictions_hfb["predictions"] == "HFB Class I"]
df_class_1.describe()

       HFB Class I  HFB Class II
count   181.000000    181.000000
mean      0.945580      0.054420
std       0.089312      0.089312
min       0.538164      0.000100
25%       0.940798      0.005514
50%       0.982366      0.017634
75%       0.994486      0.059202
max       0.999900      0.461836

In [102]:
df_class_1 = df_class_1[df_class_1["HFB Class I"]>=0.999]
df_class_1

     HFB Class I  HFB Class II        id  predictions
12      0.999174      0.000826   g593.t1  HFB Class I
26      0.999900      0.000100  g1462.t1  HFB Class I
34      0.999580      0.000420  g1846.t1  HFB Class I
41      0.999054      0.000946  g2055.t1  HFB Class I
52      0.999070      0.000930  g2670.t1  HFB Class I
89      0.999053      0.000947  g4323.t1  HFB Class I
174     0.999116      0.000884  g8895.t1  HFB Class I

In [103]:
df_class_2 = df_class_2[df_class_2["HFB Class II"]>=0.97]
df_class_2

    HFB Class I  HFB Class II        id   predictions
11     0.022956      0.977044   g581.t1  HFB Class II
56     0.012381      0.987619  g2972.t1  HFB Class II
66     0.011628      0.988372  g3395.t1  HFB Class II

In [84]:
df_predictions_hfb[df_predictions_hfb["id"] == "g3395.t1"]

    HFB Class I  HFB Class II        id   predictions
66     0.011628      0.988372  g3395.t1  HFB Class II

In [85]:
df_predictions_hfb[df_predictions_hfb["id"] == "g581.t1"]

    HFB Class I  HFB Class II       id   predictions
11     0.022956      0.977044  g581.t1  HFB Class II

In [86]:
df_predictions_hfb_cps[df_predictions_hfb_cps["id"] == "g2314.t1"]

    CPs  HFB        id predictions
61  1.0  0.0  g2314.t1         CPs

In [108]:
df_raw = pd.read_csv("../../results/mapping_p_salina/filter_sequences.csv")
df_raw

            id                                           sequence  len
0        g1.t1  MVNLTPWRKAQTCEDNGMGSSTATSTQEKDGPRPRWNLGILSDPQT...  743
1        g3.t1  MNGPSWMRRRPSNIGSGSIPARATLSTPMADGTHPYQDSPSIRLLS...  350
2        g4.t1  MASPQQIRTKLTDLLKIQHPVMLAGMNVAAGPKLAAAVTNAGGLGV...  358
3        g5.t1  MFTTASRVAALRARSRVAQPFAASSVSISGQAAQNFRALHSKRLAR...  547
4        g6.t1  MAAQELRYDGQTVVVTGAGGGLGREYAVFYGSRGANVVVNDLGGSF...  903
...        ...                                                ...  ...
8575  g9531.t1  LGVGITVKALYNNTNSFDSIINLEKATTATNELNAFIRSNATELLV...   75
8576  g9532.t1  EHPDTLTSVSQLGSVLSSQGKYDEAEAMHRRALEGREKALGFEHPD...   78
8577  g9533.t1  MHRRALEGSENALGLEHPDTLTSVSQLGSVLSSQGKYDEAEAMHRR...   68
8578  g9534.t1  FLSLILAQQCRIATALEQVVGHLARMGGGLGGGDSDDDESEPDGLG...   69
8579  g9535.t1  MHRRDLEGSEKALGFEHPDTLTSVSQLGSVLSSQGKYDEAEAMHRR...   59

[8580 rows x 3 columns]

In [110]:
df_raw[df_raw["id"] == "g2972.t1"]

            id                                           sequence  len
2654  g2972.t1  MKFDSTILLASLAASVVAAPAPYPNYAALKRYVDTTGSQKLPAHFV...  368